# -*- coding: utf-8 -*-
"""Palindrome_Check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Check if a given string is a palindrome.

Two-Pointer - O(n)
"""

def is_palindrome(s):
    s = ''.join(filter(str.isalnum, s)).lower()  # Remove non-alphanumeric & lowercase
    left, right = 0, len(s) - 1

    while left < right:
        if s[left] != s[right]:
            return False
        left += 1
        right -= 1
    return True

print(is_palindrome("A man, a plan, a canal: Panama"))
print(is_palindrome("Panama"))