# -*- coding: utf-8 -*-
"""Sort a Stack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Sort the elements of a stack.

Solution: Use recursion to pop elements, then insert them in the correct position.

- **Explanation**: Sorting a stack using recursion requires moving all elements in and out of the stack multiple times. The time complexity arises from repeatedly inserting elements in sorted order (O(n) for each of the n elements), leading to an overall O(n^2) complexity.

- **Time Complexity**: O(n^2)
- **Space Complexity**: O(n)
"""

def sort_stack(stack):
    if not stack:
        return
    temp = stack.pop()
    sort_stack(stack)
    insert_sorted(stack, temp)

def insert_sorted(stack, temp):
    if not stack or stack[-1] <= temp:
        stack.append(temp)
        return
    item = stack.pop()
    insert_sorted(stack, temp)
    stack.append(item)