# -*- coding: utf-8 -*-
"""Merging Two Sorted Linked Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Merge two sorted linked lists into one sorted linked list.

Explanation: Iterate through both lists, comparing elements, and attach the smaller node to the result list.

---


Time Complexity: O(n + m), where n and m are the lengths of the two lists.


Space Complexity: O(1)
"""

def merge_sorted_lists(l1, l2):
    dummy = ListNode()
    current = dummy
    while l1 and l2:
        if l1.val < l2.val:
            current.next = l1
            l1 = l1.next
        else:
            current.next = l2
            l2 = l2.next
        current = current.next
    current.next = l1 or l2
    return dummy.next