# -*- coding: utf-8 -*-
"""Happy Number Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Determine if a number is a "happy number."

Explanation: A happy number eventually reaches 1 when replaced by the sum of the squares of its digits. If it falls into a cycle, it’s not a happy number.

---


Time Complexity: O(log n)

Space Complexity: O(log n)
"""

def is_happy(n):
    def get_sum_of_squares(num):
        total = 0
        while num > 0:
            digit = num % 10
            total += digit * digit
            num //= 10
        return total

    seen = set()
    while n != 1 and n not in seen:
        seen.add(n)
        n = get_sum_of_squares(n)
    return n == 1