# -*- coding: utf-8 -*-
"""Next Greater Element

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Find the next greater element for each element in an array.

Solution: Use a stack to keep track of indices and find the next greater element.

- **Explanation**: We iterate over the array of elements once (O(n)), using a stack to track the indices of elements whose next greater element hasn't been found yet. Each element is pushed and popped from the stack once, so the time complexity is O(n). The stack stores up to n indices, resulting in O(n) space complexity.

- **Time Complexity**: O(n)
- **Space Complexity**: O(n)
"""

def next_greater_element(nums):
    stack = []
    result = [-1] * len(nums)
    for i in range(len(nums)):
        while stack and nums[i] > nums[stack[-1]]:
            index = stack.pop()
            result[index] = nums[i]
        stack.append(i)
    return result