# -*- coding: utf-8 -*-
"""Balanced Parentheses

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Check if parentheses, brackets, or braces in a string are balanced.

- **Explanation**: We iterate through each character in the string once (O(n)), and we store the opening brackets in a stack, which can hold at most n elements in the worst case (O(n)).

- **Time Complexity**: O(n)
- **Space Complexity**: O(n)
"""

def isValid(s):
    stack = []
    mapping = {')': '(', '}': '{', ']': '['}

    for char in s:
        if char in mapping:
            top = stack.pop() if stack else '#'
            if mapping[char] != top:
                return False
        else:
            stack.append(char)

    return not stack

print(isValid("()[]{}"))
print(isValid("(]"))