# -*- coding: utf-8 -*-
"""Reversal of a Linked List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Reverse a given linked list.

Explanation: This solution uses three pointers:
prev, current, and next_node to reverse the links between nodes iteratively.


---


Time Complexity: O(n)

Space Complexity: O(1)
"""

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def reverse_linked_list(head):
    prev = None
    current = head
    while current:
        next_node = current.next
        current.next = prev
        prev = current
        current = next_node
    return prev