# -*- coding: utf-8 -*-
"""TwoSum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Given an array and a target sum, find two numbers that add up to the target.

Using HashMap - O(n)
"""

def two_sum(nums, target):
    seen = {}  # Dictionary to store visited elements
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]  # Returns indices
        seen[num] = i
    return []  # No solution found

print(two_sum([2, 11, 15], 13))  # Output: [0, 1]