# -*- coding: utf-8 -*-
"""Implement Queue Using Stacks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Implement a queue using two stacks.

Algorithm (Two Stacks - s1 and s2):

1. Enqueue (Push to s1).
2. Dequeue (Pop from s2):

- If s2 is empty, move all elements from s1 to s2.
- Pop from s2.

3. Time Complexity: O(1) for enqueue,
O(n) for dequeue
"""

class QueueUsingStacks:
    def __init__(self):
        self.s1 = []
        self.s2 = []

    def enqueue(self, x):
        self.s1.append(x)

    def dequeue(self):
        if not self.s2:
            while self.s1:
                self.s2.append(self.s1.pop())
        return self.s2.pop() if self.s2 else None

q = QueueUsingStacks()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)

print(q.dequeue())
print(q.dequeue())