# -*- coding: utf-8 -*-
"""Removing Duplicates from a Linked List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Remove duplicates from a sorted linked list.

Explanation: Iterate through the list, and if the current node's value is the same as the next one, skip the next node.

---


Time Complexity: O(n)

Space Complexity: O(1)
"""

def remove_duplicates(head):
    current = head
    while current and current.next:
        if current.val == current.next.val:
            current.next = current.next.next
        else:
            current = current.next
    return head