# -*- coding: utf-8 -*-
"""Reverse_an_Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJBRltSdVnAyNILUZiRBNOuOgLirSXTw

Problem: Reverse an array in place.

Two-Pointer - O(n)
"""

def reverse_array(arr):
    left, right = 0, len(arr) - 1
    while left < right:
        arr[left], arr[right] = arr[right], arr[left]  # Swap elements
        left += 1
        right -= 1
    return arr

print(reverse_array([1, 2, 3, 4, 5]))